### PR TITLE
make ref account optional in settle funds

### PR DESCRIPTION
**Pull request by abrzezinski94**

### CODE REVIEW

**Comment by brittcyr** [comment]
This needs a change in the idl, I can do that in a couple hours

**Comment by abrzezinski94** [comment]
> This needs a change in the idl, I can do that in a couple hours

Are you sure it’s already optional in rust?

**Comment by brittcyr** [comment]
> Contributor

Looks like it was supposed to be
https://github.com/CKS-Systems/manifest/blob/77e51df363ff72c2b713bd1995f713c4dd104b21/programs/ui-wrapper/src/instruction.rs#L115
but wasnt done correctly for idl

program is supposed to handle it
https://github.com/CKS-Systems/manifest/blob/77e51df363ff72c2b713bd1995f713c4dd104b21/programs/ui-wrapper/src/processors/settle_funds.rs#L67

**Comment by brittcyr** [comment]
Doing it here
https://github.com/CKS-Systems/manifest/pull/264

**Pull request closed without merging**
