### PR TITLE
Auto publish npm github action

### PR DESCRIPTION
**Pull request by brittcyr**

### CODE REVIEW

**Review by TovarishFin — APPROVED** [review]
I've never used a setup like this. Though I don't normally have any sort of CI setups in general. This auto increments the version in package.json and publishes the package when any updates to main, right?

**Comment by brittcyr** [comment]
> I've never used a setup like this. Though I don't normally have any sort of CI setups in general. This auto increments the version in package.json and publishes the package when any updates to main, right?

Does not auto increment. When you merge a change it always tries to publish. If version already exists, it doe nothing. If you bumped the version, it publishes.

**Comment by mschneider** [comment]
this is quite a radical degree of automation, but interested to try it out

**Comment by brittcyr** [comment]
> this is quite a radical degree of automation, but i'm down to try it out

It's what we did in dual to avoiding sharing around keys and to make it more predictable when and what version would be published.
There are risks that sharing secret key with github can bring, but as long as we control repo, fine by me

**Pull request merged**
