### PR TITLE
Show the best 5, not worst 5 orders

### PR DESCRIPTION
**Pull request by brittcyr**

### CODE REVIEW

**Review by DonDuala — APPROVED** [review]
Where are these showing?

**Comment by brittcyr** [comment]
Screenshot 2024-11-10 at 5 00 11 PM

**Comment by DonDuala** [comment]
Are you sure there are better orders? Haven't seen any bug on the UI

**Comment by DonDuala** [comment]
Are you sure there are better orders? Haven't seen any bug on the UI

**Comment by brittcyr** [comment]
Earlier today when peacock was on, we couldnt see our orders because of the stinky orders. Will wait to deploy til we are back up and can verify

**Comment by brittcyr** [comment]
Screenshot 2024-11-10 at 5 09 27 PM

**Review by mschneider — APPROVED** [review]

**Pull request merged**
