### PR TITLE
Back to 64 byte blocks for the market

### PR DESCRIPTION
**Pull request by brittcyr**
image

### CODE REVIEW

**Comment by brittcyr** [comment]
Will follow up with client code change after review of program

**Comment by brittcyr** [comment]
without price caching, this is what I get
    {
        "name": "MFX_50",
        "value": 8356,
        "unit": "CU",
        "range": "",
        "extra": ""
    },
    {
        "name": "MFX_95",
        "value": 12343,
        "unit": "CU",
        "range": "",
        "extra": ""
    },
    {
        "name": "MFX_99",
        "value": 13951,
        "unit": "CU",
        "range": "",
        "extra": ""
    }


a noticeable increase

**Comment by mschneider** [comment]
we are still 5% away from target on the 50, adding 20% on top of that for a 25% decrease in rent (after we reduced it by 9999%) seems like a step in the wrong direction. It's trading an insignificant rent improvement for significant cu efficiency.

**Comment by brittcyr** [comment]
> we are still 5% away from target on the 50, adding 20% on top of that for a 25% decrease in rent (after we reduced it by 9999%) seems like a step in the wrong direction. It's trading an insignificant rent improvement for significant cu efficiency.

I'll keep this open in case we do want to try to cache things and squeeze back the CU, but agree that as it stands now, the decision would be no go.

**Pull request closed without merging**
