### PR TITLE
Organize & clean up readme

### PR DESCRIPTION
**Pull request by DonDuala**

### CODE REVIEW

**Review by brittcyr — APPROVED** [review]

**Comment by brittcyr** [comment]
Maybe mention that 1.0.0 is deployed

**Comment by brittcyr** [comment]
https://github.com/CKS-Systems/manifest/releases/tag/program-v1.0.0

**Comment by DonDuala** [comment]
Go for it not sure how you're thinking of displaying

**Comment by brittcyr** [comment]
Just anywhere saying currently deployed version is the 1.0.0 release

Fixing the code now. Was broken because of certora change

**Pull request merged**
